package Lbs;

import javax.swing.JOptionPane;

public class EnterBook extends javax.swing.JFrame {

    public int UPDATE_BOOK_ID = 0;
    DatabaseCon DATABASE_CON = new DatabaseCon();
    boolean VIEW_ONLY = false;

    public EnterBook() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_category = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_name = new javax.swing.JTextField();
        txt_code = new javax.swing.JTextField();
        btn_add = new javax.swing.JButton();
        btn_clear = new javax.swing.JButton();
        lbl_heading = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(890, 650));
        setResizable(false);
        getContentPane().setLayout(null);

        txt_category.setText(" ");
        getContentPane().add(txt_category);
        txt_category.setBounds(300, 280, 310, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Category");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(240, 280, 60, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Name");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(240, 245, 60, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Code");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(240, 210, 60, 30);

        txt_name.setText(" ");
        getContentPane().add(txt_name);
        txt_name.setBounds(300, 245, 310, 30);

        txt_code.setText(" ");
        getContentPane().add(txt_code);
        txt_code.setBounds(300, 210, 310, 30);

        btn_add.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btn_add.setText("Add");
        btn_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addActionPerformed(evt);
            }
        });
        getContentPane().add(btn_add);
        btn_add.setBounds(530, 320, 80, 30);

        btn_clear.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btn_clear.setText("Clear");
        btn_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clearActionPerformed(evt);
            }
        });
        getContentPane().add(btn_clear);
        btn_clear.setBounds(440, 320, 80, 30);

        lbl_heading.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lbl_heading.setForeground(new java.awt.Color(0, 51, 255));
        lbl_heading.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_heading.setText("Enter Book");
        getContentPane().add(lbl_heading);
        lbl_heading.setBounds(0, 10, 864, 49);

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Lbs/background_image.jpg"))); // NOI18N
        getContentPane().add(jLabel10);
        jLabel10.setBounds(-30, -100, 950, 850);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clearActionPerformed
        clearFeilds();
    }//GEN-LAST:event_btn_clearActionPerformed

    private void btn_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addActionPerformed
        // TODO add your handling code here:

        if (UPDATE_BOOK_ID > 0) {
            updateProductDb();
        } else {
            addProductDb();
        }
    }//GEN-LAST:event_btn_addActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EnterBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EnterBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EnterBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EnterBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>


        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EnterBook().setVisible(true);
            }
        });
    }

    private void addProductDb() {

        if (!VIEW_ONLY) {
            if (!txt_code.getText().trim().isEmpty()) {
                if (!txt_name.getText().trim().isEmpty()) {
                    if (!txt_category.getText().trim().isEmpty()) {
                        if (!DATABASE_CON.isThisCodeAlreadyUsed(txt_code.getText().trim())) {
                            if (DATABASE_CON.saveNewBook(txt_code.getText().trim(), txt_name.getText().trim(), txt_category.getText().trim())) {
                                clearFeilds();
                                JOptionPane.showMessageDialog(null, "new book added!", "ERROR", 1);
                            } else {
                                JOptionPane.showMessageDialog(null, "Something went wrong. Please try again!", "ERROR", 2);
                            }
                        } else {
                            JOptionPane.showMessageDialog(null, "This code already used!", "ERROR", 2);
                        }
                    } else {
                        JOptionPane.showMessageDialog(null, "Please check category!", "ERROR", 2);
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Please check name!", "ERROR", 2);
                }
            } else {
                JOptionPane.showMessageDialog(null, "Please check code!", "ERROR", 2);
            }
        } else {
            this.dispose();
        }
    }

    private void updateProductDb() {
        if (!txt_code.getText().trim().isEmpty()) {
            if (!txt_name.getText().trim().isEmpty()) {
                if (!txt_category.getText().trim().isEmpty()) {
                    if (DATABASE_CON.updateBook(UPDATE_BOOK_ID, txt_code.getText().trim(), txt_name.getText().trim(), txt_category.getText().trim())) {
                        clearFeilds();
                        JOptionPane.showMessageDialog(null, "book updated!", "ERROR", 1);
                    } else {
                        JOptionPane.showMessageDialog(null, "Something went wrong. Please try again!", "ERROR", 2);
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Please check category!", "ERROR", 2);
                }
            } else {
                JOptionPane.showMessageDialog(null, "Please check name!", "ERROR", 2);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Please check code!", "ERROR", 2);
        }
    }

    private void clearFeilds() {

        txt_code.setText("");
        txt_name.setText("");
        txt_category.setText("");
        UPDATE_BOOK_ID = 0;
        btn_add.setText("Add");
        txt_code.setEditable(true);

        txt_code.setEditable(true);
        txt_name.setEditable(true);
        txt_category.setEditable(true);
        btn_clear.setEnabled(true);
        VIEW_ONLY = false;

    }

    public void setUpdateBookData(int id, String code, String name, String category, String type) {

        if (type.equals("EDIT")) {

            UPDATE_BOOK_ID = id;
            txt_code.setEditable(false);
            txt_code.setText(code);
            txt_name.setText(name);
            txt_category.setText(category);
            btn_add.setText("Update");
            lbl_heading.setText("Update Book");
        } else {
            VIEW_ONLY = true;
            txt_code.setText(code);
            txt_name.setText(name);
            txt_category.setText(category);
            txt_code.setEditable(false);
            txt_name.setEditable(false);
            txt_category.setEditable(false);
            btn_clear.setEnabled(false);
            lbl_heading.setText("Views Book");
            btn_add.setText("Close");
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_add;
    private javax.swing.JButton btn_clear;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lbl_heading;
    private javax.swing.JTextField txt_category;
    private javax.swing.JTextField txt_code;
    private javax.swing.JTextField txt_name;
    // End of variables declaration//GEN-END:variables
}
