package Lbs;

import java.awt.Color;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.JOptionPane;

public class EnterBookReturn extends javax.swing.JFrame {
    
    public int UPDATE_BOOK_ID = 0;
    DatabaseCon DATABASE_CON = new DatabaseCon();
    boolean VIEW_ONLY = false;
    
    String SELECTED_BOOK_CODE = "", SELECTED_BOOK_NAME = "";
    ArrayList SELECTED_RETURN_BOOK_DATA;
    SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
    
    public EnterBookReturn() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lbl_book_status = new javax.swing.JLabel();
        txt_student = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        date_return_date = new com.toedter.calendar.JDateChooser();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txta_remarks = new javax.swing.JTextArea();
        txt_name = new javax.swing.JTextField();
        txt_code = new javax.swing.JTextField();
        btn_add = new javax.swing.JButton();
        btn_clear = new javax.swing.JButton();
        lbl_heading = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(890, 650));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Remarks");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(225, 315, 70, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Student");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(220, 150, 70, 30);

        lbl_book_status.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        getContentPane().add(lbl_book_status);
        lbl_book_status.setBounds(302, 222, 550, 20);

        txt_student.setEditable(false);
        txt_student.setText(" ");
        txt_student.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_studentKeyPressed(evt);
            }
        });
        getContentPane().add(txt_student);
        txt_student.setBounds(300, 150, 310, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Return Date");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(225, 280, 70, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Book Name");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(225, 245, 70, 30);

        date_return_date.setDateFormatString("dd/MM/yyyy");
        date_return_date.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        date_return_date.setMinSelectableDate(new java.util.Date(1672515076000L));
        getContentPane().add(date_return_date);
        date_return_date.setBounds(300, 280, 310, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Book Code");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(220, 190, 70, 30);

        txta_remarks.setColumns(20);
        txta_remarks.setRows(5);
        jScrollPane1.setViewportView(txta_remarks);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(300, 315, 310, 96);

        txt_name.setEditable(false);
        txt_name.setText(" ");
        getContentPane().add(txt_name);
        txt_name.setBounds(300, 245, 310, 30);

        txt_code.setText(" ");
        txt_code.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_codeKeyPressed(evt);
            }
        });
        getContentPane().add(txt_code);
        txt_code.setBounds(300, 190, 310, 30);

        btn_add.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btn_add.setText("Return");
        btn_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addActionPerformed(evt);
            }
        });
        getContentPane().add(btn_add);
        btn_add.setBounds(530, 420, 80, 30);

        btn_clear.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btn_clear.setText("Clear");
        btn_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clearActionPerformed(evt);
            }
        });
        getContentPane().add(btn_clear);
        btn_clear.setBounds(440, 420, 80, 30);

        lbl_heading.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lbl_heading.setForeground(new java.awt.Color(0, 51, 255));
        lbl_heading.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_heading.setText("Book Return");
        getContentPane().add(lbl_heading);
        lbl_heading.setBounds(0, 10, 864, 49);

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Lbs/background_image.jpg"))); // NOI18N
        getContentPane().add(jLabel10);
        jLabel10.setBounds(-30, -100, 950, 850);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clearActionPerformed
        clearFeilds();
    }//GEN-LAST:event_btn_clearActionPerformed

    private void btn_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addActionPerformed
        saveBookIssueData();
    }//GEN-LAST:event_btn_addActionPerformed

    private void txt_codeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_codeKeyPressed
        if (evt.getKeyCode() == 10) {
            validateTheBookBeforeReturn();
        }
    }//GEN-LAST:event_txt_codeKeyPressed

    private void txt_studentKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_studentKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_studentKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EnterBookReturn().setVisible(true);
            }
        });
    }
    
    private void addProductDb() {

//        if (!VIEW_ONLY) {
//            if (!txt_code.getText().trim().isEmpty()) {
//                if (!txt_name.getText().trim().isEmpty()) {
//                    if (!txt_category.getText().trim().isEmpty()) {
//                        if (!DATABASE_CON.isThisCodeAlreadyUsed(txt_code.getText().trim())) {
//                            if (DATABASE_CON.saveNewBook(txt_code.getText().trim(), txt_name.getText().trim(), txt_category.getText().trim())) {
//                                clearFeilds();
//                                JOptionPane.showMessageDialog(null, "new book added!", "ERROR", 1);
//                            } else {
//                                JOptionPane.showMessageDialog(null, "Something went wrong. Please try again!", "ERROR", 2);
//                            }
//                        } else {
//                            JOptionPane.showMessageDialog(null, "This code already used!", "ERROR", 2);
//                        }
//                    } else {
//                        JOptionPane.showMessageDialog(null, "Please check category!", "ERROR", 2);
//                    }
//                } else {
//                    JOptionPane.showMessageDialog(null, "Please check name!", "ERROR", 2);
//                }
//            } else {
//                JOptionPane.showMessageDialog(null, "Please check code!", "ERROR", 2);
//            }
//        } else {
//            this.dispose();
//        }
    }
    
    private void updateProductDb() {
//        if (!txt_code.getText().trim().isEmpty()) {
//            if (!txt_name.getText().trim().isEmpty()) {
//                if (!txt_category.getText().trim().isEmpty()) {
//                    if (DATABASE_CON.updateBook(UPDATE_BOOK_ID, txt_code.getText().trim(), txt_name.getText().trim(), txt_category.getText().trim())) {
//                        clearFeilds();
//                        JOptionPane.showMessageDialog(null, "book updated!", "ERROR", 1);
//                    } else {
//                        JOptionPane.showMessageDialog(null, "Something went wrong. Please try again!", "ERROR", 2);
//                    }
//                } else {
//                    JOptionPane.showMessageDialog(null, "Please check category!", "ERROR", 2);
//                }
//            } else {
//                JOptionPane.showMessageDialog(null, "Please check name!", "ERROR", 2);
//            }
//        } else {
//            JOptionPane.showMessageDialog(null, "Please check code!", "ERROR", 2);
//        }
    }
    
    private void validateTheBookBeforeReturn() {
        
        if (!txt_code.getText().trim().equals("")) {
            SELECTED_BOOK_CODE = txt_code.getText().trim();
            SELECTED_BOOK_NAME = DATABASE_CON.isThisBookCodeValid(SELECTED_BOOK_CODE);
            if (!SELECTED_BOOK_NAME.equals("")) {
                txt_name.setText(SELECTED_BOOK_NAME);
                SELECTED_RETURN_BOOK_DATA = DATABASE_CON.isThisBookCanReturn(SELECTED_BOOK_CODE);
                if (SELECTED_RETURN_BOOK_DATA != null) {
                    txt_student.setText(SELECTED_RETURN_BOOK_DATA.get(1).toString());
                    lbl_book_status.setForeground(Color.BLUE);
                    lbl_book_status.setText("Selected book is available for return!");
                } else {
                    lbl_book_status.setForeground(Color.RED);
                    lbl_book_status.setText("Selected book is already return or wrong code!");
                }
            } else {
                lbl_book_status.setForeground(Color.RED);
                lbl_book_status.setText("Insert book code is not valid!");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Please check book code!", "ERROR", 2);
        }
    }
    
    private void saveBookIssueData() {
        if (!SELECTED_BOOK_CODE.equals("") && !SELECTED_BOOK_NAME.equals("")) {
            if (date_return_date.getDate() != null && !date_return_date.getDate().toString().equals("")) {
                if (DATABASE_CON.saveReturnBookDataToDb(Integer.valueOf(SELECTED_RETURN_BOOK_DATA.get(0).toString()), dateFormat.format(date_return_date.getDate()), txta_remarks.getText().trim())) {
                    clearFeilds();
                    JOptionPane.showMessageDialog(null, "Book return is success!", "SUCCESS", 1);
                } else {
                    JOptionPane.showMessageDialog(null, "Something went wrong. Please try again!", "ERROR", 2);
                }
            } else {
                JOptionPane.showMessageDialog(null, "Please select the return date!", "ERROR", 2);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Please check book availability before issue!", "ERROR", 2);
        }
    }
    
    private void clearFeilds() {
        
        SELECTED_BOOK_CODE = "";
        SELECTED_BOOK_NAME = "";
        SELECTED_RETURN_BOOK_DATA = null;
        txt_student.setText("");
        txta_remarks.setText("");
        txt_name.setText("");
        txt_code.setText("");
        date_return_date.setDate(null);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_add;
    private javax.swing.JButton btn_clear;
    private com.toedter.calendar.JDateChooser date_return_date;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_book_status;
    private javax.swing.JLabel lbl_heading;
    private javax.swing.JTextField txt_code;
    private javax.swing.JTextField txt_name;
    private javax.swing.JTextField txt_student;
    private javax.swing.JTextArea txta_remarks;
    // End of variables declaration//GEN-END:variables
}
